-- Singleton row required for 011_seed_site_settings_booking_hours.sql (UPDATE ... WHERE id = 'default').
-- After a full TRUNCATE, INSERT creates the row; ON CONFLICT preserves existing rows on re-seed.
-- Values align with SiteSettingsEntity defaults / SiteSettingsService.create when no row exists.
INSERT INTO site_settings (
  id,
  "businessName",
  "addressLine1",
  city,
  region,
  "postalCode",
  country,
  phone,
  "publicEmail",
  latitude,
  longitude,
  "openingHoursSpecJson",
  "bookingTimeZone",
  "bookingHoursSpecJson",
  "defaultLocale",
  "themeJson",
  "smsBookingNotificationsEnabled",
  "emailBookingNotificationsEnabled",
  "smsBookingRemindersEnabled",
  "emailBookingRemindersEnabled",
  "smsThankYouReceiptEnabled",
  "emailThankYouReceiptEnabled",
  "smsPaymentConfirmedEnabled",
  "emailPaymentConfirmedEnabled",
  "bookingSessionMinutes",
  "bookingBreakMinutes",
  "bookingConcurrentSeatsPerSlot",
  "createdAt",
  "updatedAt"
) VALUES (
  'default',
  'Kutz',
  '352 Van Heerden, Halfway Gardens',
  'Midrand',
  'Gauteng',
  '1685',
  'ZA',
  '+27 00 000 0000',
  '',
  -25.995,
  28.13,
  '["Mo-Su 07:00-20:00"]',
  'Africa/Johannesburg',
  '[]',
  'en',
  '{"brandBrown":"#000000","brandCream":"#F5F5F5","brandOrange":"#1A1A1A","brandWhite":"#FFFFFF","background":"#FFFFFF","foreground":"#000000","primary":"#000000","muted":"#737373","card":"#FFFFFF","border":"#E5E5E5"}',
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  15,
  10,
  5,
  now(),
  now()
)
ON CONFLICT (id) DO NOTHING;
